# Generated by Django 5.0.6 on 2024-06-18 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlhit',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='urlhit',
            name='short_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
