# Generated by Django 5.0.6 on 2024-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_urlhit_user_agent_urlhit_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhit',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
        ),
    ]
